# WolfWhale LMS SwiftLint Configuration
# Enforces code quality standards for A+++ grade

# Enabled rules
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules (too noisy for large codebase migration)
disabled_rules:
  - trailing_comma
  - opening_brace
  - todo
  - line_length  # Will enable after initial cleanup

# Custom rule configurations
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 400
  error: 800

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 3
  function_level: 3

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - i
    - r
    - g
    - b
    - dx
    - dy

# Paths to include/exclude
included:
  - WolfWhale

excluded:
  - WolfWhale.xcodeproj
  - WolfWhaleTests
  - WolfWhaleUITests
  - .build
  - Packages

# Reporter
reporter: xcode
