import SwiftUI

// MARK: - Vocabulary Data

struct FrenchVocabData {
    static let allCategories: [VocabCategory] =
        [
            VocabCategory(name: "Greetings", icon: "hand.wave.fill", color1: .blue, color2: .cyan, words: greetings),
            VocabCategory(name: "Family", icon: "figure.2.and.child.holdinghands", color1: .orange, color2: .red, words: family),
            VocabCategory(name: "Food", icon: "fork.knife", color1: .orange, color2: .yellow, words: food),
            VocabCategory(name: "School", icon: "graduationcap.fill", color1: .purple, color2: .indigo, words: school),
            VocabCategory(name: "Animals", icon: "pawprint.fill", color1: .green, color2: .mint, words: animals),
            VocabCategory(name: "Body Parts", icon: "figure.stand", color1: .red, color2: .orange, words: bodyParts),
            VocabCategory(name: "Colours", icon: "paintpalette.fill", color1: .indigo, color2: .purple, words: colours),
            VocabCategory(name: "Numbers", icon: "number", color1: .teal, color2: .blue, words: numbers),
            VocabCategory(name: "Weather", icon: "cloud.sun.fill", color1: .cyan, color2: .blue, words: weather),
            VocabCategory(name: "Clothing", icon: "tshirt.fill", color1: .brown, color2: .orange, words: clothing),
        ]

    static let greetings: [FrenchWord] =
        [
            FrenchWord(french: "Bonjour", english: "Hello / Good morning", phonetic: "bohn-ZHOOR"),
            FrenchWord(french: "Bonsoir", english: "Good evening", phonetic: "bohn-SWAHR"),
            FrenchWord(french: "Salut", english: "Hi / Bye (informal)", phonetic: "sah-LOO"),
            FrenchWord(french: "Au revoir", english: "Goodbye", phonetic: "oh ruh-VWAHR"),
            FrenchWord(french: "Merci", english: "Thank you", phonetic: "mehr-SEE"),
            FrenchWord(french: "Merci beaucoup", english: "Thank you very much", phonetic: "mehr-SEE boh-KOO"),
            FrenchWord(french: "S'il vous plait", english: "Please (formal)", phonetic: "seel voo PLEH"),
            FrenchWord(french: "S'il te plait", english: "Please (informal)", phonetic: "seel tuh PLEH"),
            FrenchWord(french: "De rien", english: "You're welcome", phonetic: "duh RYEHN"),
            FrenchWord(french: "Excusez-moi", english: "Excuse me", phonetic: "ek-skew-ZAY mwah"),
            FrenchWord(french: "Pardon", english: "Sorry / Pardon", phonetic: "par-DOHN"),
            FrenchWord(french: "Comment allez-vous?", english: "How are you? (formal)", phonetic: "koh-MOHN tah-LAY voo"),
            FrenchWord(french: "Comment ca va?", english: "How are you? (informal)", phonetic: "koh-MOHN sah VAH"),
            FrenchWord(french: "Ca va bien", english: "I'm doing well", phonetic: "sah vah BYEHN"),
            FrenchWord(french: "Bonne nuit", english: "Good night", phonetic: "bohn NWEE"),
            FrenchWord(french: "Bienvenue", english: "Welcome", phonetic: "byehn-vuh-NOO"),
            FrenchWord(french: "A bientot", english: "See you soon", phonetic: "ah byehn-TOH"),
            FrenchWord(french: "A demain", english: "See you tomorrow", phonetic: "ah duh-MEHN"),
            FrenchWord(french: "Enchant\u{00E9}", english: "Nice to meet you", phonetic: "ohn-shahn-TAY"),
            FrenchWord(french: "Bonne journ\u{00E9}e", english: "Have a good day", phonetic: "bohn zhoor-NAY"),
            FrenchWord(french: "Oui", english: "Yes", phonetic: "WEE"),
            FrenchWord(french: "Non", english: "No", phonetic: "NOHN"),
        ]

    static let family: [FrenchWord] =
        [
            FrenchWord(french: "La m\u{00E8}re", english: "Mother", phonetic: "lah MEHR"),
            FrenchWord(french: "Le p\u{00E8}re", english: "Father", phonetic: "luh PEHR"),
            FrenchWord(french: "La soeur", english: "Sister", phonetic: "lah SUHR"),
            FrenchWord(french: "Le fr\u{00E8}re", english: "Brother", phonetic: "luh FREHR"),
            FrenchWord(french: "La grand-m\u{00E8}re", english: "Grandmother", phonetic: "lah grahn-MEHR"),
            FrenchWord(french: "Le grand-p\u{00E8}re", english: "Grandfather", phonetic: "luh grahn-PEHR"),
            FrenchWord(french: "La tante", english: "Aunt", phonetic: "lah TAHNT"),
            FrenchWord(french: "L'oncle", english: "Uncle", phonetic: "LOHNKL"),
            FrenchWord(french: "Le cousin", english: "Cousin (male)", phonetic: "luh koo-ZEHN"),
            FrenchWord(french: "La cousine", english: "Cousin (female)", phonetic: "lah koo-ZEEN"),
            FrenchWord(french: "Le fils", english: "Son", phonetic: "luh FEES"),
            FrenchWord(french: "La fille", english: "Daughter", phonetic: "lah FEE-yuh"),
            FrenchWord(french: "Le b\u{00E9}b\u{00E9}", english: "Baby", phonetic: "luh bay-BAY"),
            FrenchWord(french: "La famille", english: "Family", phonetic: "lah fah-MEE-yuh"),
            FrenchWord(french: "Les parents", english: "Parents", phonetic: "lay pah-RAHN"),
            FrenchWord(french: "Les enfants", english: "Children", phonetic: "layz ahn-FAHN"),
            FrenchWord(french: "Le mari", english: "Husband", phonetic: "luh mah-REE"),
            FrenchWord(french: "La femme", english: "Wife / Woman", phonetic: "lah FAHM"),
            FrenchWord(french: "Le neveu", english: "Nephew", phonetic: "luh nuh-VUH"),
            FrenchWord(french: "La ni\u{00E8}ce", english: "Niece", phonetic: "lah NYEHS"),
        ]

    static let food: [FrenchWord] =
        [
            FrenchWord(french: "Le pain", english: "Bread", phonetic: "luh PEHN"),
            FrenchWord(french: "Le fromage", english: "Cheese", phonetic: "luh froh-MAHZH"),
            FrenchWord(french: "La pomme", english: "Apple", phonetic: "lah POHM"),
            FrenchWord(french: "Le lait", english: "Milk", phonetic: "luh LEH"),
            FrenchWord(french: "L'eau", english: "Water", phonetic: "LOH"),
            FrenchWord(french: "Le poulet", english: "Chicken", phonetic: "luh poo-LEH"),
            FrenchWord(french: "Le poisson", english: "Fish", phonetic: "luh pwah-SOHN"),
            FrenchWord(french: "La soupe", english: "Soup", phonetic: "lah SOOP"),
            FrenchWord(french: "Le riz", english: "Rice", phonetic: "luh REE"),
            FrenchWord(french: "Les l\u{00E9}gumes", english: "Vegetables", phonetic: "lay lay-GOOM"),
            FrenchWord(french: "Les fruits", english: "Fruits", phonetic: "lay FRWEE"),
            FrenchWord(french: "Le g\u{00E2}teau", english: "Cake", phonetic: "luh gah-TOH"),
            FrenchWord(french: "La glace", english: "Ice cream", phonetic: "lah GLAHS"),
            FrenchWord(french: "Le beurre", english: "Butter", phonetic: "luh BUHR"),
            FrenchWord(french: "L'oeuf", english: "Egg", phonetic: "LUHF"),
            FrenchWord(french: "La carotte", english: "Carrot", phonetic: "lah kah-ROHT"),
            FrenchWord(french: "La tomate", english: "Tomato", phonetic: "lah toh-MAHT"),
            FrenchWord(french: "Le chocolat", english: "Chocolate", phonetic: "luh shoh-koh-LAH"),
            FrenchWord(french: "La poutine", english: "Poutine", phonetic: "lah poo-TEEN"),
            FrenchWord(french: "Le sirop d'\u{00E9}rable", english: "Maple syrup", phonetic: "luh see-ROH day-RAHBL"),
            FrenchWord(french: "La cr\u{00EA}pe", english: "Crepe / Pancake", phonetic: "lah KREHP"),
        ]

    static let school: [FrenchWord] =
        [
            FrenchWord(french: "L'\u{00E9}cole", english: "School", phonetic: "lay-KOHL"),
            FrenchWord(french: "Le professeur", english: "Teacher", phonetic: "luh proh-feh-SUHR"),
            FrenchWord(french: "L'\u{00E9}l\u{00E8}ve", english: "Student", phonetic: "lay-LEHV"),
            FrenchWord(french: "Le livre", english: "Book", phonetic: "luh LEEVR"),
            FrenchWord(french: "Le cahier", english: "Notebook", phonetic: "luh kah-YAY"),
            FrenchWord(french: "Le crayon", english: "Pencil", phonetic: "luh kray-OHN"),
            FrenchWord(french: "Le stylo", english: "Pen", phonetic: "luh stee-LOH"),
            FrenchWord(french: "La classe", english: "Classroom", phonetic: "lah KLAHS"),
            FrenchWord(french: "Le bureau", english: "Desk / Office", phonetic: "luh bew-ROH"),
            FrenchWord(french: "La chaise", english: "Chair", phonetic: "lah SHEHZ"),
            FrenchWord(french: "Le tableau", english: "Board / Painting", phonetic: "luh tah-BLOH"),
            FrenchWord(french: "Les devoirs", english: "Homework", phonetic: "lay duh-VWAHR"),
            FrenchWord(french: "L'examen", english: "Exam", phonetic: "leg-zah-MEHN"),
            FrenchWord(french: "La r\u{00E9}cr\u{00E9}ation", english: "Recess", phonetic: "lah ray-kray-ah-SYOHN"),
            FrenchWord(french: "Le sac \u{00E0} dos", english: "Backpack", phonetic: "luh sahk ah DOH"),
            FrenchWord(french: "La r\u{00E8}gle", english: "Ruler", phonetic: "lah REHGL"),
            FrenchWord(french: "La gomme", english: "Eraser", phonetic: "lah GOHM"),
            FrenchWord(french: "Les ciseaux", english: "Scissors", phonetic: "lay see-ZOH"),
            FrenchWord(french: "L'ordinateur", english: "Computer", phonetic: "lor-dee-nah-TUHR"),
            FrenchWord(french: "La biblioth\u{00E8}que", english: "Library", phonetic: "lah bee-blee-oh-TEHK"),
        ]

    static let animals: [FrenchWord] =
        [
            FrenchWord(french: "Le chat", english: "Cat", phonetic: "luh SHAH"),
            FrenchWord(french: "Le chien", english: "Dog", phonetic: "luh SHYEHN"),
            FrenchWord(french: "L'oiseau", english: "Bird", phonetic: "lwah-ZOH"),
            FrenchWord(french: "Le poisson", english: "Fish", phonetic: "luh pwah-SOHN"),
            FrenchWord(french: "Le cheval", english: "Horse", phonetic: "luh shuh-VAHL"),
            FrenchWord(french: "La vache", english: "Cow", phonetic: "lah VAHSH"),
            FrenchWord(french: "Le cochon", english: "Pig", phonetic: "luh koh-SHOHN"),
            FrenchWord(french: "Le mouton", english: "Sheep", phonetic: "luh moo-TOHN"),
            FrenchWord(french: "Le lapin", english: "Rabbit", phonetic: "luh lah-PEHN"),
            FrenchWord(french: "La souris", english: "Mouse", phonetic: "lah soo-REE"),
            FrenchWord(french: "Le loup", english: "Wolf", phonetic: "luh LOO"),
            FrenchWord(french: "L'ours", english: "Bear", phonetic: "LOORS"),
            FrenchWord(french: "Le renard", english: "Fox", phonetic: "luh ruh-NAHR"),
            FrenchWord(french: "La baleine", english: "Whale", phonetic: "lah bah-LEHN"),
            FrenchWord(french: "Le dauphin", english: "Dolphin", phonetic: "luh doh-FEHN"),
            FrenchWord(french: "La tortue", english: "Turtle", phonetic: "lah tohr-TOO"),
            FrenchWord(french: "Le papillon", english: "Butterfly", phonetic: "luh pah-pee-YOHN"),
            FrenchWord(french: "L'\u{00E9}l\u{00E9}phant", english: "Elephant", phonetic: "lay-lay-FAHN"),
            FrenchWord(french: "Le singe", english: "Monkey", phonetic: "luh SEHNZH"),
            FrenchWord(french: "L'orignal", english: "Moose", phonetic: "loh-ree-NYAHL"),
            FrenchWord(french: "Le castor", english: "Beaver", phonetic: "luh kahs-TOHR"),
        ]

    static let bodyParts: [FrenchWord] =
        [
            FrenchWord(french: "La t\u{00EA}te", english: "Head", phonetic: "lah TEHT"),
            FrenchWord(french: "Les yeux", english: "Eyes", phonetic: "layz YUH"),
            FrenchWord(french: "Le nez", english: "Nose", phonetic: "luh NAY"),
            FrenchWord(french: "La bouche", english: "Mouth", phonetic: "lah BOOSH"),
            FrenchWord(french: "Les oreilles", english: "Ears", phonetic: "layz oh-RAY"),
            FrenchWord(french: "Le bras", english: "Arm", phonetic: "luh BRAH"),
            FrenchWord(french: "La main", english: "Hand", phonetic: "lah MEHN"),
            FrenchWord(french: "Le doigt", english: "Finger", phonetic: "luh DWAH"),
            FrenchWord(french: "La jambe", english: "Leg", phonetic: "lah ZHAHMB"),
            FrenchWord(french: "Le pied", english: "Foot", phonetic: "luh PYAY"),
            FrenchWord(french: "Le coeur", english: "Heart", phonetic: "luh KUHR"),
            FrenchWord(french: "Le dos", english: "Back", phonetic: "luh DOH"),
            FrenchWord(french: "Le ventre", english: "Stomach / Belly", phonetic: "luh VAHNTR"),
            FrenchWord(french: "Les cheveux", english: "Hair", phonetic: "lay shuh-VUH"),
            FrenchWord(french: "Le genou", english: "Knee", phonetic: "luh zhuh-NOO"),
            FrenchWord(french: "L'\u{00E9}paule", english: "Shoulder", phonetic: "lay-POHL"),
            FrenchWord(french: "Le cou", english: "Neck", phonetic: "luh KOO"),
            FrenchWord(french: "Les dents", english: "Teeth", phonetic: "lay DAHN"),
            FrenchWord(french: "La langue", english: "Tongue", phonetic: "lah LAHNGH"),
            FrenchWord(french: "Le visage", english: "Face", phonetic: "luh vee-ZAHZH"),
        ]

    static let colours: [FrenchWord] =
        [
            FrenchWord(french: "Rouge", english: "Red", phonetic: "ROOZH"),
            FrenchWord(french: "Bleu", english: "Blue", phonetic: "BLUH"),
            FrenchWord(french: "Vert", english: "Green", phonetic: "VEHR"),
            FrenchWord(french: "Jaune", english: "Yellow", phonetic: "ZHOHN"),
            FrenchWord(french: "Orange", english: "Orange", phonetic: "oh-RAHNZH"),
            FrenchWord(french: "Violet", english: "Purple", phonetic: "vyoh-LEH"),
            FrenchWord(french: "Rose", english: "Pink", phonetic: "ROHZ"),
            FrenchWord(french: "Blanc", english: "White", phonetic: "BLAHN"),
            FrenchWord(french: "Noir", english: "Black", phonetic: "NWAHR"),
            FrenchWord(french: "Gris", english: "Grey", phonetic: "GREE"),
            FrenchWord(french: "Brun", english: "Brown", phonetic: "BRUHN"),
            FrenchWord(french: "Dor\u{00E9}", english: "Gold", phonetic: "doh-RAY"),
            FrenchWord(french: "Argent\u{00E9}", english: "Silver", phonetic: "ahr-zhahn-TAY"),
            FrenchWord(french: "Turquoise", english: "Turquoise", phonetic: "toor-KWAHZ"),
            FrenchWord(french: "Beige", english: "Beige", phonetic: "BEHZH"),
            FrenchWord(french: "Marron", english: "Chestnut brown", phonetic: "mah-ROHN"),
            FrenchWord(french: "Mauve", english: "Mauve", phonetic: "MOHV"),
            FrenchWord(french: "Indigo", english: "Indigo", phonetic: "ehn-dee-GOH"),
            FrenchWord(french: "Clair", english: "Light (colour)", phonetic: "KLEHR"),
            FrenchWord(french: "Fonc\u{00E9}", english: "Dark (colour)", phonetic: "fohn-SAY"),
        ]

    static let numbers: [FrenchWord] =
        [
            FrenchWord(french: "Un", english: "One (1)", phonetic: "UHN"),
            FrenchWord(french: "Deux", english: "Two (2)", phonetic: "DUH"),
            FrenchWord(french: "Trois", english: "Three (3)", phonetic: "TRWAH"),
            FrenchWord(french: "Quatre", english: "Four (4)", phonetic: "KAHTR"),
            FrenchWord(french: "Cinq", english: "Five (5)", phonetic: "SEHNK"),
            FrenchWord(french: "Six", english: "Six (6)", phonetic: "SEES"),
            FrenchWord(french: "Sept", english: "Seven (7)", phonetic: "SEHT"),
            FrenchWord(french: "Huit", english: "Eight (8)", phonetic: "WEET"),
            FrenchWord(french: "Neuf", english: "Nine (9)", phonetic: "NUHF"),
            FrenchWord(french: "Dix", english: "Ten (10)", phonetic: "DEES"),
            FrenchWord(french: "Onze", english: "Eleven (11)", phonetic: "OHNZ"),
            FrenchWord(french: "Douze", english: "Twelve (12)", phonetic: "DOOZ"),
            FrenchWord(french: "Treize", english: "Thirteen (13)", phonetic: "TREHZ"),
            FrenchWord(french: "Quatorze", english: "Fourteen (14)", phonetic: "kah-TOHRZ"),
            FrenchWord(french: "Quinze", english: "Fifteen (15)", phonetic: "KAHNZ"),
            FrenchWord(french: "Vingt", english: "Twenty (20)", phonetic: "VEHN"),
            FrenchWord(french: "Trente", english: "Thirty (30)", phonetic: "TRAHNT"),
            FrenchWord(french: "Cinquante", english: "Fifty (50)", phonetic: "sehn-KAHNT"),
            FrenchWord(french: "Cent", english: "One hundred (100)", phonetic: "SAHN"),
            FrenchWord(french: "Mille", english: "One thousand (1000)", phonetic: "MEEL"),
        ]

    static let weather: [FrenchWord] =
        [
            FrenchWord(french: "Il fait soleil", english: "It's sunny", phonetic: "eel feh soh-LAY"),
            FrenchWord(french: "Il pleut", english: "It's raining", phonetic: "eel PLUH"),
            FrenchWord(french: "Il neige", english: "It's snowing", phonetic: "eel NEHZH"),
            FrenchWord(french: "Il fait chaud", english: "It's hot", phonetic: "eel feh SHOH"),
            FrenchWord(french: "Il fait froid", english: "It's cold", phonetic: "eel feh FRWAH"),
            FrenchWord(french: "Il fait beau", english: "It's nice out", phonetic: "eel feh BOH"),
            FrenchWord(french: "Il fait mauvais", english: "The weather is bad", phonetic: "eel feh moh-VEH"),
            FrenchWord(french: "Le vent", english: "Wind", phonetic: "luh VAHN"),
            FrenchWord(french: "Il fait du vent", english: "It's windy", phonetic: "eel feh doo VAHN"),
            FrenchWord(french: "Le nuage", english: "Cloud", phonetic: "luh new-AHZH"),
            FrenchWord(french: "L'orage", english: "Storm", phonetic: "loh-RAHZH"),
            FrenchWord(french: "La temp\u{00EA}te", english: "Tempest / Blizzard", phonetic: "lah tahm-PEHT"),
            FrenchWord(french: "Le tonnerre", english: "Thunder", phonetic: "luh toh-NEHR"),
            FrenchWord(french: "L'\u{00E9}clair", english: "Lightning", phonetic: "lay-KLEHR"),
            FrenchWord(french: "L'arc-en-ciel", english: "Rainbow", phonetic: "lahrk-ahn-SYEHL"),
            FrenchWord(french: "La pluie", english: "Rain", phonetic: "lah PLOO-ee"),
            FrenchWord(french: "La neige", english: "Snow", phonetic: "lah NEHZH"),
            FrenchWord(french: "Le brouillard", english: "Fog", phonetic: "luh broo-YAHR"),
            FrenchWord(french: "La glace", english: "Ice", phonetic: "lah GLAHS"),
            FrenchWord(french: "Le verglas", english: "Black ice", phonetic: "luh vehr-GLAH"),
        ]

    static let clothing: [FrenchWord] =
        [
            FrenchWord(french: "Le chandail", english: "Sweater", phonetic: "luh shahn-DAH-yuh"),
            FrenchWord(french: "Le pantalon", english: "Pants", phonetic: "luh pahn-tah-LOHN"),
            FrenchWord(french: "La chemise", english: "Shirt", phonetic: "lah shuh-MEEZ"),
            FrenchWord(french: "La robe", english: "Dress", phonetic: "lah ROHB"),
            FrenchWord(french: "La jupe", english: "Skirt", phonetic: "lah ZHOOP"),
            FrenchWord(french: "Les chaussures", english: "Shoes", phonetic: "lay shoh-SOOR"),
            FrenchWord(french: "Les bottes", english: "Boots", phonetic: "lay BOHT"),
            FrenchWord(french: "Le manteau", english: "Coat", phonetic: "luh mahn-TOH"),
            FrenchWord(french: "La tuque", english: "Winter hat (toque)", phonetic: "lah TOOK"),
            FrenchWord(french: "Les mitaines", english: "Mittens", phonetic: "lay mee-TEHN"),
            FrenchWord(french: "L'\u{00E9}charpe", english: "Scarf", phonetic: "lay-SHAHRP"),
            FrenchWord(french: "Les chaussettes", english: "Socks", phonetic: "lay shoh-SEHT"),
            FrenchWord(french: "Le chapeau", english: "Hat", phonetic: "luh shah-POH"),
            FrenchWord(french: "Les lunettes", english: "Glasses", phonetic: "lay loo-NEHT"),
            FrenchWord(french: "La ceinture", english: "Belt", phonetic: "lah sehn-TOOR"),
            FrenchWord(french: "Le pyjama", english: "Pajamas", phonetic: "luh pee-zhah-MAH"),
            FrenchWord(french: "Le maillot de bain", english: "Swimsuit", phonetic: "luh my-OH duh BEHN"),
            FrenchWord(french: "Les gants", english: "Gloves", phonetic: "lay GAHN"),
            FrenchWord(french: "La veste", english: "Jacket", phonetic: "lah VEHST"),
            FrenchWord(french: "Le costume de neige", english: "Snowsuit", phonetic: "luh kohs-TOOM duh NEHZH"),
        ]
}
